//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        private int Status { get; set; }
        public string DestinationAddress { get; set; }
        public System.Guid ExternalDeliveryIdentifier { get; set; }
        public string SourceAddress { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
