//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryInfo
    {
        public int Id { get; set; }
        public string SourceAddress { get; set; }
        public string DestinationAddress { get; set; }
        public string OrderNumber { get; set; }
        public System.Guid DeliveryIdentifier { get; set; }
        public string DeliveryNotificationAddress { get; set; }
        public int Status { get; set; }
    }
}
